### ISSUE TITLE
Uwspólnienie kodu i konfiguracji między frontendem i backendem

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon#12]
Ponieważ oba repozytoria będą używać tego samego kodu do obsługi błędów i już teraz następuje replikacja konfiguracji (eg: [tu](https://github.com/PZCharon/charon-backend/blob/develop/lib/Charon/Users.pm#L16) i [tu](https://github.com/PZCharon/charon-frontend/blob/develop/configs/forms.yml#L2)) proponuję przemyśleć dwa nastepujące rozwiązania:

1. Założyć dodatkowe subrepozytorium na wspólne pliki i skonfigurować oba repozytoria aby używały najnowszej wersji nowego subrepo. Dzięki temu będzie można zrobić checkout np. samego frontendu i zostaną pobrane wszystkie potrzebne do jego działania pliki.

2. Umieścić część wspólną w głównym repo Charona. Nie trzeba będzie tworzyć nowych repozytoriów ale uzależnimy frontend i backend od bycia checkoutowanym jako potomek głównego repo.

Jestem osobiście za opcją nr 1, chyba że zaproponowane zostanie coś lepszego.

**Comment by s-nez** [comment]
Podana replikacja jest tylko tymczasowa, bo docelowo frontend nie będzie trzymał definicji formularzy, tylko konstruował je na podstawie danych z backendu.

**Comment by mnatan** [comment]
Wciąż pozostaje problem replikacji niezaimplementowanego jeszcze Charon::Error i innych potencjalnych bibliotek.

Możemy to jednak zbagatelizować i uznać że będzie ich zbyt niewielie żeby tworzyć osobne repozytorium. Wszak po to wprowadziliśmy podział na frontend i backend żeby wyraźnie ustalić odpowiedzialność poszczególnych modułów i uniknąć takich replikacji.

**Comment by mnatan** [comment]
Closing, uwspólnienie stworzy niepotrzebne komplikacje.
