### ISSUE TITLE
Spotkanie w sprawie zebrania specyfikacji

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon#13]
Na spotkaniu 01.04.2016 @morlinq i @ovk6 zgłosiły się do spotkania z Romanem w celu zebrania wymagań. Issue polega na przekazaniu zebranej dokumentacji zespołowi, więc powinno zakończyć się po wykonaniu:

- #10

**Comment by ovk6** [comment]
Specyfikacje dodałam

**Comment by mnatan** [comment]
:+1:
