### ISSUE TITLE
Wybór logo projektu

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon#6]
Na chwilę obecną używamy wszędzie księżyca. Jeśli ktos ma coś przeciw, to jest issue na inne propozycje.

**Comment by s-nez** [comment]
To nie jest byle księżyc, to jest [Charon](https://en.wikipedia.org/wiki/Charon_%28moon%29).

**Comment by s-nez** [comment]
Logo jest mało istotne, w ostatecznym produkcie i tak go nie będzie widać, bo zostanie zastąpione przez logo UJ. Brak propozycji przez ostatni miesiąc, zamykam.
